name: Close Pull Request

on:
    pull_request_target:
        types: [ opened ]

permissions:
    actions: write
    checks: write
    pull-requests: write

jobs:
    PR:
        uses: cashier-provider/.github/.github/workflows/close-pull-request.yml@main
